apiVersion: v1
kind: Service
metadata:
  name: fastapi-crud-service
spec:
  selector:
    app: fastapi-crud-hpa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
